
package org.itson.banco.presentacion;

import javax.swing.JOptionPane;
import org.itson.banco.dtos.ClienteDTO;
import org.itson.banco.dtos.CuentaDTO;
import org.itson.banco.dtos.TransferenciaDTO;
import org.itson.banco.negocio.NegocioException;
import org.itson.banco.negocio.TransferenciaBO;
import org.itson.banco.persistencia.ConexionBD;
import org.itson.banco.persistencia.TransferenciaDAO;

/**
 *
 * @author emyla
 */
public class ConfirmarTransferenciaFORM extends javax.swing.JFrame {

    ControladorTransferencia controlador;
    ClienteDTO cliente;
    TransferenciaDTO transferenciaDTO;
    CuentaDTO cuentaOrigen;
    /**
     * Creates new form ConfirmarTransferenciaFORM
     */
    public ConfirmarTransferenciaFORM(ControladorTransferencia controlador, ClienteDTO cliente, TransferenciaDTO transferenciaDTO, CuentaDTO cuentaOrigen) {
        this.controlador = controlador;
        this.cliente = cliente;
        this.transferenciaDTO = transferenciaDTO;
        this.cuentaOrigen = cuentaOrigen;
        initComponents();
        mostrarCuentas();
    }
    
    private void mostrarCuentas() {
        String noCuentaOrigen = String.valueOf(transferenciaDTO.getCuentaOrigen());
        lblNoCuentaOrigen.setText(noCuentaOrigen);
        String noCuentaDestino = String.valueOf(transferenciaDTO.getCuentaDestino());
        lblNoCuentaDestino.setText(noCuentaDestino);
        String montoTransferir = String.valueOf(transferenciaDTO.getMonto());
        lblMontoTansferir.setText(montoTransferir);
        
        String saldoRestante = String.valueOf((cuentaOrigen.getSaldoCuenta() - transferenciaDTO.getMonto()));
        lblPesosRestantes.setText(saldoRestante);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBanner4 = new javax.swing.JPanel();
        btnOperaciones3 = new javax.swing.JButton();
        btnPaginaCuenta3 = new javax.swing.JButton();
        btnEditarDatos3 = new javax.swing.JButton();
        btnPaginaCuenta7 = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        pnlDatosCuenta = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jpnCuentaDestino = new javax.swing.JPanel();
        lblCuentaDestino = new javax.swing.JLabel();
        lblNoCuenta2 = new javax.swing.JLabel();
        lblNoCuentaDestino = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpnCuentaOrigen = new javax.swing.JPanel();
        lblCuentaOrigen = new javax.swing.JLabel();
        lblNoCuenta1 = new javax.swing.JLabel();
        lblNoCuentaOrigen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSaldoRestante = new javax.swing.JLabel();
        lblMontoTansferir = new javax.swing.JLabel();
        lblPesosRestantes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Confirmar transferencia");

        pnlBanner4.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanner4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlBanner4.setAlignmentY(0.0F);

        btnOperaciones3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnOperaciones3.setText("Operaciones");
        btnOperaciones3.setToolTipText("");
        btnOperaciones3.setBorder(null);
        btnOperaciones3.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnOperaciones3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperaciones3ActionPerformed(evt);
            }
        });

        btnPaginaCuenta3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnPaginaCuenta3.setText("Cuentas");
        btnPaginaCuenta3.setToolTipText("");
        btnPaginaCuenta3.setBorder(null);
        btnPaginaCuenta3.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaCuenta3ActionPerformed(evt);
            }
        });

        btnEditarDatos3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnEditarDatos3.setText("Perfil");
        btnEditarDatos3.setToolTipText("");
        btnEditarDatos3.setBorder(null);
        btnEditarDatos3.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnEditarDatos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDatos3ActionPerformed(evt);
            }
        });

        btnPaginaCuenta7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPaginaCuenta7.setText("VOYAGE");
        btnPaginaCuenta7.setToolTipText("");
        btnPaginaCuenta7.setBorder(null);
        btnPaginaCuenta7.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaCuenta7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBanner4Layout = new javax.swing.GroupLayout(pnlBanner4);
        pnlBanner4.setLayout(pnlBanner4Layout);
        pnlBanner4Layout.setHorizontalGroup(
            pnlBanner4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnPaginaCuenta7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnPaginaCuenta3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOperaciones3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnEditarDatos3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        pnlBanner4Layout.setVerticalGroup(
            pnlBanner4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner4Layout.createSequentialGroup()
                .addGroup(pnlBanner4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaginaCuenta7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaginaCuenta3)
                    .addComponent(btnOperaciones3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarDatos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlDatos.setBackground(new java.awt.Color(217, 217, 217));

        pnlDatosCuenta.setBackground(new java.awt.Color(255, 255, 255));

        btnConfirmar.setBackground(new java.awt.Color(47, 65, 86));
        btnConfirmar.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Realizar transferencia");

        btnCancelar.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblCuentaDestino.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblCuentaDestino.setText("Cuenta destino");

        lblNoCuenta2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblNoCuenta2.setText("No. Cuenta");

        lblNoCuentaDestino.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblNoCuentaDestino.setText("0000");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("VOYAGE");

        javax.swing.GroupLayout jpnCuentaDestinoLayout = new javax.swing.GroupLayout(jpnCuentaDestino);
        jpnCuentaDestino.setLayout(jpnCuentaDestinoLayout);
        jpnCuentaDestinoLayout.setHorizontalGroup(
            jpnCuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCuentaDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnCuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnCuentaDestinoLayout.createSequentialGroup()
                        .addComponent(lblNoCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNoCuentaDestino))
                    .addGroup(jpnCuentaDestinoLayout.createSequentialGroup()
                        .addGroup(jpnCuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnCuentaDestinoLayout.setVerticalGroup(
            jpnCuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCuentaDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCuentaDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnCuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCuentaOrigen.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblCuentaOrigen.setText("Cuenta origen");

        lblNoCuenta1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblNoCuenta1.setText("No. Cuenta");

        lblNoCuentaOrigen.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblNoCuentaOrigen.setText("0000");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("VOYAGE");

        javax.swing.GroupLayout jpnCuentaOrigenLayout = new javax.swing.GroupLayout(jpnCuentaOrigen);
        jpnCuentaOrigen.setLayout(jpnCuentaOrigenLayout);
        jpnCuentaOrigenLayout.setHorizontalGroup(
            jpnCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCuentaOrigenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnCuentaOrigenLayout.createSequentialGroup()
                        .addComponent(lblNoCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNoCuentaOrigen))
                    .addGroup(jpnCuentaOrigenLayout.createSequentialGroup()
                        .addGroup(jpnCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnCuentaOrigenLayout.setVerticalGroup(
            jpnCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCuentaOrigenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCuentaOrigen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoCuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblSaldoRestante.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblSaldoRestante.setText("Saldo Restante");

        lblMontoTansferir.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblMontoTansferir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMontoTansferir.setText("$00.00");

        lblPesosRestantes.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblPesosRestantes.setText("$00.00");

        javax.swing.GroupLayout pnlDatosCuentaLayout = new javax.swing.GroupLayout(pnlDatosCuenta);
        pnlDatosCuenta.setLayout(pnlDatosCuentaLayout);
        pnlDatosCuentaLayout.setHorizontalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                        .addComponent(lblSaldoRestante)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                                .addComponent(jpnCuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMontoTansferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                                .addComponent(lblPesosRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(254, 254, 254)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jpnCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(212, 212, 212))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(231, 231, 231))))))
        );
        pnlDatosCuentaLayout.setVerticalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTitulo)
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblMontoTansferir))
                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpnCuentaDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnCuentaOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldoRestante)
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPesosRestantes)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(btnConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlBanner4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBanner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de querer volver?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            // Acción si el usuario dice SÍ
            controlador.loginExitoso(cliente);
            this.dispose(); // cerrar ventana actual
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        
        TransferenciaBO transferenciaBO = new TransferenciaBO(new TransferenciaDAO(new ConexionBD()));
        int folio = 0;
        try {
            folio = transferenciaBO.realizarTransferencia(transferenciaDTO);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de transferencia", JOptionPane.ERROR_MESSAGE);
        }
        dispose();
        controlador.abrirTransferenciaExitosa(folio);
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnOperaciones3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperaciones3ActionPerformed
        controlador.abrirHistorial();
        this.dispose();
    }//GEN-LAST:event_btnOperaciones3ActionPerformed

    private void btnPaginaCuenta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuenta3ActionPerformed
        controlador.loginExitoso(cliente);
        this.dispose();
    }//GEN-LAST:event_btnPaginaCuenta3ActionPerformed

    private void btnEditarDatos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarDatos3ActionPerformed

    private void btnPaginaCuenta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuenta7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaginaCuenta7ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEditarDatos;
    private javax.swing.JButton btnEditarDatos1;
    private javax.swing.JButton btnEditarDatos2;
    private javax.swing.JButton btnEditarDatos3;
    private javax.swing.JButton btnOperaciones;
    private javax.swing.JButton btnOperaciones1;
    private javax.swing.JButton btnOperaciones2;
    private javax.swing.JButton btnOperaciones3;
    private javax.swing.JButton btnPaginaCuenta;
    private javax.swing.JButton btnPaginaCuenta1;
    private javax.swing.JButton btnPaginaCuenta2;
    private javax.swing.JButton btnPaginaCuenta3;
    private javax.swing.JButton btnPaginaCuenta4;
    private javax.swing.JButton btnPaginaCuenta5;
    private javax.swing.JButton btnPaginaCuenta6;
    private javax.swing.JButton btnPaginaCuenta7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jpnCuentaDestino;
    private javax.swing.JPanel jpnCuentaOrigen;
    private javax.swing.JLabel lblCuentaDestino;
    private javax.swing.JLabel lblCuentaOrigen;
    private javax.swing.JLabel lblMontoTansferir;
    private javax.swing.JLabel lblNoCuenta1;
    private javax.swing.JLabel lblNoCuenta2;
    private javax.swing.JLabel lblNoCuentaDestino;
    private javax.swing.JLabel lblNoCuentaOrigen;
    private javax.swing.JLabel lblPesosRestantes;
    private javax.swing.JLabel lblSaldoRestante;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBanner1;
    private javax.swing.JPanel pnlBanner2;
    private javax.swing.JPanel pnlBanner3;
    private javax.swing.JPanel pnlBanner4;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatosCuenta;
    // End of variables declaration//GEN-END:variables
}
