/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.banco.presentacion;

import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.itson.banco.dtos.ClienteDTO;
import org.itson.banco.dtos.CuentaDTO;
import org.itson.banco.negocio.ClienteBO;

/**
 *
 * @author emyla
 */
public class CreacionCuentaExitosaFORM extends javax.swing.JFrame {

    private static final Logger LOGGER = Logger.getLogger(CreacionCuentaExitosaFORM.class.getName());
    private ControladorTransferencia controlador;
    private ClienteDTO cliente;
    private CuentaDTO nuevaCuenta;
    /**
     * Creates new form ConfirmarCreacionCuentaFORM
     */
    public CreacionCuentaExitosaFORM(ControladorTransferencia controlador, ClienteDTO cliente, CuentaDTO nuevaCuenta) {
        this.controlador = controlador;
        this.cliente = cliente;
        this.nuevaCuenta = nuevaCuenta;
        initComponents();
        cargarTodo();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        pnlDatosCuenta = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        txtNumCuenta = new javax.swing.JTextField();
        lblNumCuenta = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        lblMonto = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        pnlBanner1 = new javax.swing.JPanel();
        btnOperaciones = new javax.swing.JButton();
        btnPaginaCuenta = new javax.swing.JButton();
        btnEditarDatos = new javax.swing.JButton();
        btnPaginaCuenta1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Éxito");
        setBackground(new java.awt.Color(245, 239, 235));

        pnlDatos.setBackground(new java.awt.Color(217, 217, 217));

        pnlDatosCuenta.setBackground(new java.awt.Color(255, 255, 255));

        btnConfirmar.setBackground(new java.awt.Color(200, 217, 230));
        btnConfirmar.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cuenta creada con éxito");
        lblTitulo.setToolTipText("");

        txtNumCuenta.setEditable(false);
        txtNumCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCuentaActionPerformed(evt);
            }
        });

        lblNumCuenta.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblNumCuenta.setText("Número de Cuenta:");

        txtMonto.setEditable(false);
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        lblMonto.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblMonto.setText("Monto:");

        lblNombreCliente.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblNombreCliente.setText("Nombre del titular:");

        txtNombreCompleto.setEditable(false);
        txtNombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCompletoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosCuentaLayout = new javax.swing.GroupLayout(pnlDatosCuenta);
        pnlDatosCuenta.setLayout(pnlDatosCuentaLayout);
        pnlDatosCuentaLayout.setHorizontalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNombreCliente)
                                .addComponent(lblMonto)
                                .addComponent(txtNombreCompleto)
                                .addComponent(txtMonto)
                                .addComponent(txtNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNumCuenta)))
                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnlDatosCuentaLayout.setVerticalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(10, 10, 10)
                .addComponent(lblNumCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBanner1.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanner1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlBanner1.setAlignmentY(0.0F);

        btnOperaciones.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnOperaciones.setText("Operaciones");
        btnOperaciones.setToolTipText("");
        btnOperaciones.setBorder(null);
        btnOperaciones.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacionesActionPerformed(evt);
            }
        });

        btnPaginaCuenta.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnPaginaCuenta.setText("Cuentas");
        btnPaginaCuenta.setToolTipText("");
        btnPaginaCuenta.setBorder(null);
        btnPaginaCuenta.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaCuentaActionPerformed(evt);
            }
        });

        btnEditarDatos.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnEditarDatos.setText("Perfil");
        btnEditarDatos.setToolTipText("");
        btnEditarDatos.setBorder(null);
        btnEditarDatos.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnEditarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDatosActionPerformed(evt);
            }
        });

        btnPaginaCuenta1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPaginaCuenta1.setText("VOYAGE");
        btnPaginaCuenta1.setToolTipText("");
        btnPaginaCuenta1.setBorder(null);
        btnPaginaCuenta1.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaCuenta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBanner1Layout = new javax.swing.GroupLayout(pnlBanner1);
        pnlBanner1.setLayout(pnlBanner1Layout);
        pnlBanner1Layout.setHorizontalGroup(
            pnlBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnPaginaCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnPaginaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnEditarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        pnlBanner1Layout.setVerticalGroup(
            pnlBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner1Layout.createSequentialGroup()
                .addGroup(pnlBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaginaCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaginaCuenta)
                    .addComponent(btnOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 12, Short.MAX_VALUE)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBanner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBanner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        controlador.loginExitoso(cliente);
        this.dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void cargarNombreCompleto(){
        txtNombreCompleto.setText(String.valueOf(cliente.toString()));
    }    
    
    private void cargarNumeroCuentaNuevo(){
        txtNumCuenta.setText(String.valueOf(nuevaCuenta.getNumeroCuenta()));
    }
    
    private void cargarMonto(){
        txtMonto.setText(String.valueOf(nuevaCuenta.getSaldoCuenta()));
    }
    
    private void cargarTodo(){
        cargarNombreCompleto();
        cargarNumeroCuentaNuevo();
        cargarMonto();
    }
    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        cargarMonto();        
    }//GEN-LAST:event_txtMontoActionPerformed

    private void txtNumCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCuentaActionPerformed
        cargarNumeroCuentaNuevo();
    }//GEN-LAST:event_txtNumCuentaActionPerformed

    private void txtNombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCompletoActionPerformed
        cargarNombreCompleto();
    }//GEN-LAST:event_txtNombreCompletoActionPerformed

    private void btnOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacionesActionPerformed
        controlador.abrirHistorial();
        this.dispose();
    }//GEN-LAST:event_btnOperacionesActionPerformed

    private void btnPaginaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuentaActionPerformed
        controlador.loginExitoso(cliente);
        this.dispose();
    }//GEN-LAST:event_btnPaginaCuentaActionPerformed

    private void btnEditarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarDatosActionPerformed

    private void btnPaginaCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuenta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaginaCuenta1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEditarDatos;
    private javax.swing.JButton btnOperaciones;
    private javax.swing.JButton btnPaginaCuenta;
    private javax.swing.JButton btnPaginaCuenta1;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNumCuenta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBanner1;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatosCuenta;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtNumCuenta;
    // End of variables declaration//GEN-END:variables
}
