/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.banco.presentacion;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.itson.banco.dtos.ClienteDTO;
import org.itson.banco.dtos.CuentaDTO;
import org.itson.banco.negocio.ICuentaBO;

/**
 *
 * @author nafbr
 */
public class CuentasFORM extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CuentasFORM.class.getName());
    private final ControladorTransferencia controlador;
    private final ClienteDTO cliente;//Para mover los datos del cliente loggeado
    private final ICuentaBO cuentaBO;

    /**
     * Creates new form CuentasFORM
     */
    public CuentasFORM(ControladorTransferencia controlador, ClienteDTO cliente, ICuentaBO cuentaBO) {
        this.controlador = controlador;
        this.cliente = cliente;
        this.cuentaBO = cuentaBO;
        initComponents();
        setLocationRelativeTo(null);
        configurarVentana();

    }

    private void configurarVentana() {
        // Poner nombre del cliente
        lblNombreCliente.setText(cliente.getNombres() + " " + cliente.getApellidoPaterno());
        cbxCuentasUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarSaldo();
            }
        });
        cargarCuentas();
    }

    private void cargarCuentas() {
        try {
            controlador.cargarCuentasDelCliente(cliente.getId(), cuentaBO);
            List<String> numerosCuenta = controlador.obtenerNumerosDeCuenta();
            DefaultComboBoxModel modeloCombo = (DefaultComboBoxModel) this.cbxCuentasUsuario.getModel();
            modeloCombo.removeAllElements();
            
            if (numerosCuenta.isEmpty()) {
                modeloCombo.addElement("No tiene cuentas aún");
                cbxCuentasUsuario.setEnabled(false); 
                btnTransferir.setEnabled(false); 
                lblSaldoCuenta.setText("0.00");
                
            } else {
                for (String numero : numerosCuenta) {
                    modeloCombo.addElement(numero);
                }

                cbxCuentasUsuario.setEnabled(true);
                btnTransferir.setEnabled(true);
                cbxCuentasUsuario.setSelectedIndex(0); 
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar cuentas: " + ex.getMessage());
        }
    }

    private void actualizarSaldo() {
        Object seleccionado = cbxCuentasUsuario.getSelectedItem();

        if (seleccionado != null) {
            String numeroSeleccionado = seleccionado.toString();
            
            if (!numeroSeleccionado.equals("No tiene cuentas aún")) {
                double saldo = controlador.obtenerSaldo(numeroSeleccionado);
                lblSaldoCuenta.setText(String.format("%.2f", saldo));
                return;
            }
        }
        
        lblSaldoCuenta.setText("0.00");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBanner = new javax.swing.JPanel();
        btnPaginaCuenta = new javax.swing.JButton();
        lblVoyage = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();
        btnOperaciones = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        lblHola = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        pnlDatosCuenta = new javax.swing.JPanel();
        pnlCuentas = new javax.swing.JPanel();
        cbxCuentasUsuario = new javax.swing.JComboBox<>();
        lblNumCuenta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDatosCuenta = new javax.swing.JButton();
        lblSaldoDisponible = new javax.swing.JLabel();
        lblSignoDinero = new javax.swing.JLabel();
        btnTransferir = new javax.swing.JButton();
        lblSaldoCuenta = new javax.swing.JLabel();
        btnAgregarCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuentas del usuario");
        setBackground(new java.awt.Color(245, 239, 235));

        pnlBanner.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanner.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlBanner.setAlignmentY(0.0F);

        btnPaginaCuenta.setBackground(new java.awt.Color(86, 124, 141));
        btnPaginaCuenta.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnPaginaCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnPaginaCuenta.setText("Cuentas");
        btnPaginaCuenta.setToolTipText("");
        btnPaginaCuenta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPaginaCuenta.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta.addActionListener(this::btnPaginaCuentaActionPerformed);

        lblVoyage.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblVoyage.setText("VOYAGE");

        lblIcono.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        lblIcono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIcono.setText("Usuario...");

        btnAyuda.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnAyuda.setText("Ayuda");
        btnAyuda.setToolTipText("");
        btnAyuda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAyuda.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnAyuda.addActionListener(this::btnAyudaActionPerformed);

        btnOperaciones.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnOperaciones.setText("Operaciones");
        btnOperaciones.setToolTipText("");
        btnOperaciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOperaciones.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnOperaciones.addActionListener(this::btnOperacionesActionPerformed);

        javax.swing.GroupLayout pnlBannerLayout = new javax.swing.GroupLayout(pnlBanner);
        pnlBanner.setLayout(pnlBannerLayout);
        pnlBannerLayout.setHorizontalGroup(
            pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBannerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblVoyage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPaginaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        pnlBannerLayout.setVerticalGroup(
            pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnPaginaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblVoyage))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBannerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIcono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlDatos.setBackground(new java.awt.Color(217, 217, 217));

        lblHola.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblHola.setText("Hola,");

        lblNombreCliente.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblNombreCliente.setText("cliente");

        pnlDatosCuenta.setBackground(new java.awt.Color(255, 255, 255));

        pnlCuentas.setBackground(new java.awt.Color(200, 217, 230));

        cbxCuentasUsuario.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        cbxCuentasUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCuentasUsuario.addActionListener(this::cbxCuentasUsuarioActionPerformed);

        lblNumCuenta.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblNumCuenta.setText("No. Cuenta");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("VOYAGE");

        btnDatosCuenta.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnDatosCuenta.setText("Datos de la cuenta");
        btnDatosCuenta.addActionListener(this::btnDatosCuentaActionPerformed);

        javax.swing.GroupLayout pnlCuentasLayout = new javax.swing.GroupLayout(pnlCuentas);
        pnlCuentas.setLayout(pnlCuentasLayout);
        pnlCuentasLayout.setHorizontalGroup(
            pnlCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCuentasLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(btnDatosCuenta))
                    .addGroup(pnlCuentasLayout.createSequentialGroup()
                        .addComponent(lblNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cbxCuentasUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCuentasLayout.setVerticalGroup(
            pnlCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCuentasUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnDatosCuenta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblSaldoDisponible.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblSaldoDisponible.setText("Saldo disponible");

        lblSignoDinero.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblSignoDinero.setText("$");

        btnTransferir.setBackground(new java.awt.Color(200, 217, 230));
        btnTransferir.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(this::btnTransferirActionPerformed);

        lblSaldoCuenta.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblSaldoCuenta.setText("0");

        btnAgregarCuenta.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnAgregarCuenta.setText("Agregar Cuenta Nueva");
        btnAgregarCuenta.setBorder(null);
        btnAgregarCuenta.addActionListener(this::btnAgregarCuentaActionPerformed);

        javax.swing.GroupLayout pnlDatosCuentaLayout = new javax.swing.GroupLayout(pnlDatosCuenta);
        pnlDatosCuenta.setLayout(pnlDatosCuentaLayout);
        pnlDatosCuentaLayout.setHorizontalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSaldoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatosCuentaLayout.createSequentialGroup()
                                    .addComponent(lblSignoDinero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblSaldoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(btnTransferir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(pnlCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarCuenta)))
                .addContainerGap())
        );
        pnlDatosCuentaLayout.setVerticalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                        .addComponent(lblSaldoDisponible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSignoDinero)
                            .addComponent(lblSaldoCuenta))
                        .addGap(18, 18, 18)
                        .addComponent(btnTransferir))
                    .addComponent(pnlCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnAgregarCuenta)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreCliente))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHola)
                    .addComponent(lblNombreCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPaginaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaginaCuentaActionPerformed

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        CuentaDTO cuentaSeleccionada = seleccionarCuenta();
        if (cuentaSeleccionada != null) {
            controlador.irATransferencias(cuentaSeleccionada);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Hubo un error al recuperar la cuenta.");
        }
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void btnDatosCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosCuentaActionPerformed
        CuentaDTO cuentaSeleccionada = seleccionarCuenta();
        if (cuentaSeleccionada != null) {
            controlador.AbrirCuentaDatos(cuentaSeleccionada);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Hubo un error al recuperar la cuenta.");
        }
    }//GEN-LAST:event_btnDatosCuentaActionPerformed

    private void btnAgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCuentaActionPerformed
        controlador.abrirCrearNuevaCuenta(cliente);
        this.dispose();
    }//GEN-LAST:event_btnAgregarCuentaActionPerformed

    private void cbxCuentasUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCuentasUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCuentasUsuarioActionPerformed

    private void btnOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacionesActionPerformed
        controlador.abrirHistorial();
        this.dispose();
    }//GEN-LAST:event_btnOperacionesActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        JOptionPane.showMessageDialog(this, "Chamba quien sabe, hay q checar eso");
    }//GEN-LAST:event_btnAyudaActionPerformed

    private CuentaDTO seleccionarCuenta() {
        Object seleccionado = cbxCuentasUsuario.getSelectedItem();
        if (seleccionado == null || seleccionado.toString().equals("No tiene cuentas aún")) { 
            JOptionPane.showMessageDialog(this, "Seleccione una cuenta válida");
            return null;
        }
        String numeroCuentaSeleccionada = seleccionado.toString();
        return controlador.obtenerCuentaPorNumero(numeroCuentaSeleccionada);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCuenta;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnDatosCuenta;
    private javax.swing.JButton btnOperaciones;
    private javax.swing.JButton btnPaginaCuenta;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JComboBox<String> cbxCuentasUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblHola;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNumCuenta;
    private javax.swing.JLabel lblSaldoCuenta;
    private javax.swing.JLabel lblSaldoDisponible;
    private javax.swing.JLabel lblSignoDinero;
    private javax.swing.JLabel lblVoyage;
    private javax.swing.JPanel pnlBanner;
    private javax.swing.JPanel pnlCuentas;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatosCuenta;
    // End of variables declaration//GEN-END:variables
}
