
package org.itson.banco.presentacion;

import java.awt.Color;
import javax.swing.JOptionPane;
import org.itson.banco.dtos.ClienteDTO;
import org.itson.banco.dtos.CuentaDTO;
import org.itson.banco.negocio.NegocioException;

/**
 *
 * @author oliro
 */
public class CuentaDatosFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CuentaDatosFORM.class.getName());

    private final ControladorTransferencia controlador;
    private final ClienteDTO clienteLogueado;
    private final CuentaDTO cuentaSeleccionada;
    
    /**
     * Creates new form CuentaDatosFORM
     */
    public CuentaDatosFORM(ControladorTransferencia controlador, ClienteDTO cliente, CuentaDTO cuenta) {
        this.controlador = controlador;
        this.clienteLogueado = cliente;
        this.cuentaSeleccionada = cuenta;
        initComponents();
        cargarCuenta();
        setLocationRelativeTo(null);
    }
    
    private void cargarCuenta() {
        lblNoCuenta.setText(cuentaSeleccionada.getNumeroCuenta());
        String saldoString = String.valueOf(cuentaSeleccionada.getSaldoCuenta());
        lblSaldo.setText(saldoString);
        if(cuentaSeleccionada.getEstado().equals("activa")){
            lblEstado.setText(cuentaSeleccionada.getEstado());
            lblEstado.setForeground(Color.GREEN);
        } else {
            lblEstado.setText(cuentaSeleccionada.getEstado());
            lblEstado.setForeground(Color.RED);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlFondo2 = new javax.swing.JPanel();
        pnlFondo3 = new javax.swing.JPanel();
        pnlCuenta = new javax.swing.JPanel();
        lblTextNoCuenta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNoCuenta = new javax.swing.JLabel();
        lbltxtSaldo = new javax.swing.JLabel();
        btnDarBajaCuenta = new javax.swing.JButton();
        btnRetiroSinCue = new javax.swing.JButton();
        btnVovler = new javax.swing.JButton();
        lblSaldo = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        pnlBanner12 = new javax.swing.JPanel();
        btnOperaciones11 = new javax.swing.JButton();
        btnPaginaCuenta22 = new javax.swing.JButton();
        btnEditarDatos11 = new javax.swing.JButton();
        btnPaginaCuenta23 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos de cuenta");

        pnlFondo.setBackground(new java.awt.Color(245, 239, 235));
        pnlFondo.setForeground(new java.awt.Color(245, 239, 235));

        pnlFondo2.setBackground(new java.awt.Color(217, 217, 217));
        pnlFondo2.setForeground(new java.awt.Color(217, 217, 217));

        pnlFondo3.setBackground(new java.awt.Color(255, 255, 255));

        pnlCuenta.setBackground(new java.awt.Color(200, 217, 230));

        lblTextNoCuenta.setBackground(new java.awt.Color(0, 0, 0));
        lblTextNoCuenta.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblTextNoCuenta.setText("No. Cuenta");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("VOYAGE");

        lblNoCuenta.setBackground(new java.awt.Color(0, 0, 0));
        lblNoCuenta.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblNoCuenta.setText("*** *** *** ****");

        javax.swing.GroupLayout pnlCuentaLayout = new javax.swing.GroupLayout(pnlCuenta);
        pnlCuenta.setLayout(pnlCuentaLayout);
        pnlCuentaLayout.setHorizontalGroup(
            pnlCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCuentaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCuentaLayout.createSequentialGroup()
                        .addComponent(lblTextNoCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(lblNoCuenta)))
                .addContainerGap())
        );
        pnlCuentaLayout.setVerticalGroup(
            pnlCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextNoCuenta)
                    .addComponent(lblNoCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lbltxtSaldo.setBackground(new java.awt.Color(0, 0, 0));
        lbltxtSaldo.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lbltxtSaldo.setText("SALDO:");

        btnDarBajaCuenta.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnDarBajaCuenta.setForeground(new java.awt.Color(255, 0, 0));
        btnDarBajaCuenta.setText("<html><u>Dar de baja</u></html> ");
        btnDarBajaCuenta.addActionListener(this::btnDarBajaCuentaActionPerformed);

        btnRetiroSinCue.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnRetiroSinCue.setText("<html><u>Generar retiro<br>sin cuenta</u></html>");
        btnRetiroSinCue.addActionListener(this::btnRetiroSinCueActionPerformed);

        btnVovler.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnVovler.setText("Volver");
        btnVovler.addActionListener(this::btnVovlerActionPerformed);

        lblSaldo.setBackground(new java.awt.Color(0, 0, 0));
        lblSaldo.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblSaldo.setText("0000.00");

        lblStatus.setBackground(new java.awt.Color(0, 0, 0));
        lblStatus.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblStatus.setText("ESTADO:");

        lblEstado.setBackground(new java.awt.Color(0, 0, 0));
        lblEstado.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblEstado.setText("-");

        javax.swing.GroupLayout pnlFondo3Layout = new javax.swing.GroupLayout(pnlFondo3);
        pnlFondo3.setLayout(pnlFondo3Layout);
        pnlFondo3Layout.setHorizontalGroup(
            pnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondo3Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(pnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondo3Layout.createSequentialGroup()
                        .addComponent(btnVovler)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondo3Layout.createSequentialGroup()
                        .addGroup(pnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondo3Layout.createSequentialGroup()
                                .addComponent(btnRetiroSinCue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDarBajaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondo3Layout.createSequentialGroup()
                                .addGroup(pnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbltxtSaldo)
                                    .addComponent(lblStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(52, 52, 52))))
        );
        pnlFondo3Layout.setVerticalGroup(
            pnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondo3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltxtSaldo)
                    .addComponent(lblSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(lblEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetiroSinCue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDarBajaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnVovler)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout pnlFondo2Layout = new javax.swing.GroupLayout(pnlFondo2);
        pnlFondo2.setLayout(pnlFondo2Layout);
        pnlFondo2Layout.setHorizontalGroup(
            pnlFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondo2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnlFondo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlFondo2Layout.setVerticalGroup(
            pnlFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondo2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlFondo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlBanner12.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanner12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlBanner12.setAlignmentY(0.0F);

        btnOperaciones11.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnOperaciones11.setText("Operaciones");
        btnOperaciones11.setToolTipText("");
        btnOperaciones11.setBorder(null);
        btnOperaciones11.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnOperaciones11.addActionListener(this::btnOperaciones11ActionPerformed);

        btnPaginaCuenta22.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnPaginaCuenta22.setText("Cuentas");
        btnPaginaCuenta22.setToolTipText("");
        btnPaginaCuenta22.setBorder(null);
        btnPaginaCuenta22.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta22.addActionListener(this::btnPaginaCuenta22ActionPerformed);

        btnEditarDatos11.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnEditarDatos11.setText("Perfil");
        btnEditarDatos11.setToolTipText("");
        btnEditarDatos11.setBorder(null);
        btnEditarDatos11.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnEditarDatos11.addActionListener(this::btnEditarDatos11ActionPerformed);

        btnPaginaCuenta23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPaginaCuenta23.setText("VOYAGE");
        btnPaginaCuenta23.setToolTipText("");
        btnPaginaCuenta23.setBorder(null);
        btnPaginaCuenta23.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta23.addActionListener(this::btnPaginaCuenta23ActionPerformed);

        javax.swing.GroupLayout pnlBanner12Layout = new javax.swing.GroupLayout(pnlBanner12);
        pnlBanner12.setLayout(pnlBanner12Layout);
        pnlBanner12Layout.setHorizontalGroup(
            pnlBanner12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner12Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnPaginaCuenta23, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnPaginaCuenta22, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnOperaciones11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnEditarDatos11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        pnlBanner12Layout.setVerticalGroup(
            pnlBanner12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner12Layout.createSequentialGroup()
                .addGroup(pnlBanner12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaginaCuenta23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaginaCuenta22)
                    .addComponent(btnOperaciones11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarDatos11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(pnlFondo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBanner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBanner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(pnlFondo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVovlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVovlerActionPerformed
        dispose();
        controlador.loginExitoso(clienteLogueado);
    }//GEN-LAST:event_btnVovlerActionPerformed

    private void btnDarBajaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarBajaCuentaActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de querer cancelar esta cuenta?",
            "ATENCIÓN",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            try{
                cancelarCuenta();
            } catch(NegocioException e){
                JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
            }
            
        }
    }//GEN-LAST:event_btnDarBajaCuentaActionPerformed

    private void btnRetiroSinCueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroSinCueActionPerformed
        ControladorRetirSinCuenta controladorRSC = new ControladorRetirSinCuenta(controlador, clienteLogueado, cuentaSeleccionada);
        dispose();
        controladorRSC.abrirGenerarRetiroSinCuenta();
    }//GEN-LAST:event_btnRetiroSinCueActionPerformed

    private void btnOperaciones11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperaciones11ActionPerformed
        controlador.abrirHistorial();
        this.dispose();
    }//GEN-LAST:event_btnOperaciones11ActionPerformed

    private void btnPaginaCuenta22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuenta22ActionPerformed
        controlador.loginExitoso(clienteLogueado);
        this.dispose();
    }//GEN-LAST:event_btnPaginaCuenta22ActionPerformed

    private void btnEditarDatos11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatos11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarDatos11ActionPerformed

    private void btnPaginaCuenta23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuenta23ActionPerformed
        controlador.abrirInicioCliente(clienteLogueado);
        this.dispose();
    }//GEN-LAST:event_btnPaginaCuenta23ActionPerformed

    private void cancelarCuenta() throws NegocioException {
        controlador.cancelarCuenta(
                cuentaSeleccionada,
                clienteLogueado.getId()
        );
        JOptionPane.showMessageDialog(
                this,
                "La cuenta fue cancelada correctamente",
                "Operación exitosa",
                JOptionPane.INFORMATION_MESSAGE
        );
        dispose();
        controlador.loginExitoso(clienteLogueado);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDarBajaCuenta;
    private javax.swing.JButton btnEditarDatos11;
    private javax.swing.JButton btnOperaciones11;
    private javax.swing.JButton btnPaginaCuenta22;
    private javax.swing.JButton btnPaginaCuenta23;
    private javax.swing.JButton btnRetiroSinCue;
    private javax.swing.JButton btnVovler;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNoCuenta;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTextNoCuenta;
    private javax.swing.JLabel lbltxtSaldo;
    private javax.swing.JPanel pnlBanner12;
    private javax.swing.JPanel pnlCuenta;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlFondo2;
    private javax.swing.JPanel pnlFondo3;
    // End of variables declaration//GEN-END:variables
}
