/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.banco.presentacion;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.itson.banco.dtos.ClienteDTO;
import org.itson.banco.dtos.CuentaDTO;
import org.itson.banco.negocio.ICuentaBO;

/**
 *
 * @author nafbr
 */
public class CuentasFORM extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CuentasFORM.class.getName());
    private final ControladorTransferencia controlador;
    private final ClienteDTO cliente;//Para mover los datos del cliente loggeado
    private final ICuentaBO cuentaBO;

    /**
     * Creates new form CuentasFORM
     */
    public CuentasFORM(ControladorTransferencia controlador, ClienteDTO cliente, ICuentaBO cuentaBO) {
        this.controlador = controlador;
        this.cliente = cliente;
        this.cuentaBO = cuentaBO;
        initComponents();
        setLocationRelativeTo(null);
        configurarVentana();

    }

    private void configurarVentana() {
        // Poner nombre del cliente
        lblNombreCliente.setText(cliente.getNombres() + " " + cliente.getApellidoPaterno());
        cbxCuentasUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarSaldo();
            }
        });
        cargarCuentas();
    }

    private void cargarCuentas() {
        try {
            controlador.cargarCuentasDelCliente(cliente.getId(), cuentaBO);
            List<String> numerosCuenta = controlador.obtenerNumerosDeCuenta();
            DefaultComboBoxModel modeloCombo = (DefaultComboBoxModel) this.cbxCuentasUsuario.getModel();
            modeloCombo.removeAllElements();
            
            if (numerosCuenta.isEmpty()) {
                modeloCombo.addElement("No tiene cuentas aún");
                cbxCuentasUsuario.setEnabled(false); 
                btnTransferir.setEnabled(false); 
                lblSaldoCuenta.setText("0.00");
                
            } else {
                for (String numero : numerosCuenta) {
                    modeloCombo.addElement(numero);
                }

                cbxCuentasUsuario.setEnabled(true);
                btnTransferir.setEnabled(true);
                cbxCuentasUsuario.setSelectedIndex(0); 
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar cuentas: " + ex.getMessage());
        }
    }

    private void actualizarSaldo() {
        Object seleccionado = cbxCuentasUsuario.getSelectedItem();

        if (seleccionado != null) {
            String numeroSeleccionado = seleccionado.toString();
            
            if (!numeroSeleccionado.equals("No tiene cuentas aún")) {
                double saldo = controlador.obtenerSaldo(numeroSeleccionado);
                lblSaldoCuenta.setText(String.format("%.2f", saldo));
                return;
            }
        }
        
        lblSaldoCuenta.setText("0.00");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlBanner12 = new javax.swing.JPanel();
        btnOperaciones11 = new javax.swing.JButton();
        btnPaginaCuenta22 = new javax.swing.JButton();
        btnEditarDatos11 = new javax.swing.JButton();
        btnPaginaCuenta23 = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        lblHola = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        pnlDatosCuenta = new javax.swing.JPanel();
        pnlCuentas = new javax.swing.JPanel();
        cbxCuentasUsuario = new javax.swing.JComboBox<>();
        lblNumCuenta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDatosCuenta = new javax.swing.JButton();
        lblSaldoDisponible = new javax.swing.JLabel();
        lblSignoDinero = new javax.swing.JLabel();
        btnTransferir = new javax.swing.JButton();
        lblSaldoCuenta = new javax.swing.JLabel();
        btnAgregarCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuentas del usuario");
        setBackground(new java.awt.Color(245, 239, 235));

        jPanel1.setBackground(new java.awt.Color(245, 239, 235));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        pnlBanner12.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanner12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlBanner12.setAlignmentY(0.0F);

        btnOperaciones11.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnOperaciones11.setText("Operaciones");
        btnOperaciones11.setToolTipText("");
        btnOperaciones11.setBorder(null);
        btnOperaciones11.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnOperaciones11.addActionListener(this::btnOperaciones11ActionPerformed);

        btnPaginaCuenta22.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnPaginaCuenta22.setText("Cuentas");
        btnPaginaCuenta22.setToolTipText("");
        btnPaginaCuenta22.setBorder(null);
        btnPaginaCuenta22.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta22.addActionListener(this::btnPaginaCuenta22ActionPerformed);

        btnEditarDatos11.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnEditarDatos11.setText("Perfil");
        btnEditarDatos11.setToolTipText("");
        btnEditarDatos11.setBorder(null);
        btnEditarDatos11.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnEditarDatos11.addActionListener(this::btnEditarDatos11ActionPerformed);

        btnPaginaCuenta23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPaginaCuenta23.setText("VOYAGE");
        btnPaginaCuenta23.setToolTipText("");
        btnPaginaCuenta23.setBorder(null);
        btnPaginaCuenta23.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta23.addActionListener(this::btnPaginaCuenta23ActionPerformed);

        javax.swing.GroupLayout pnlBanner12Layout = new javax.swing.GroupLayout(pnlBanner12);
        pnlBanner12.setLayout(pnlBanner12Layout);
        pnlBanner12Layout.setHorizontalGroup(
            pnlBanner12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner12Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnPaginaCuenta23, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnPaginaCuenta22, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnOperaciones11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnEditarDatos11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        pnlBanner12Layout.setVerticalGroup(
            pnlBanner12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner12Layout.createSequentialGroup()
                .addGroup(pnlBanner12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaginaCuenta23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaginaCuenta22)
                    .addComponent(btnOperaciones11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarDatos11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlDatos.setBackground(new java.awt.Color(217, 217, 217));

        lblHola.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblHola.setText("Cuentas de");

        lblNombreCliente.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblNombreCliente.setText("cliente");

        pnlDatosCuenta.setBackground(new java.awt.Color(255, 255, 255));

        pnlCuentas.setBackground(new java.awt.Color(200, 217, 230));

        cbxCuentasUsuario.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        cbxCuentasUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCuentasUsuario.addActionListener(this::cbxCuentasUsuarioActionPerformed);

        lblNumCuenta.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblNumCuenta.setText("No. Cuenta");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("VOYAGE");

        btnDatosCuenta.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnDatosCuenta.setText("Datos de la cuenta");
        btnDatosCuenta.addActionListener(this::btnDatosCuentaActionPerformed);

        javax.swing.GroupLayout pnlCuentasLayout = new javax.swing.GroupLayout(pnlCuentas);
        pnlCuentas.setLayout(pnlCuentasLayout);
        pnlCuentasLayout.setHorizontalGroup(
            pnlCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCuentasLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(btnDatosCuenta))
                    .addGroup(pnlCuentasLayout.createSequentialGroup()
                        .addComponent(lblNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cbxCuentasUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCuentasLayout.setVerticalGroup(
            pnlCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCuentasUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnDatosCuenta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblSaldoDisponible.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblSaldoDisponible.setText("Saldo disponible");

        lblSignoDinero.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblSignoDinero.setText("$");

        btnTransferir.setBackground(new java.awt.Color(200, 217, 230));
        btnTransferir.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(this::btnTransferirActionPerformed);

        lblSaldoCuenta.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblSaldoCuenta.setText("0");

        btnAgregarCuenta.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnAgregarCuenta.setText("Agregar Cuenta Nueva");
        btnAgregarCuenta.setBorder(null);
        btnAgregarCuenta.addActionListener(this::btnAgregarCuentaActionPerformed);

        javax.swing.GroupLayout pnlDatosCuentaLayout = new javax.swing.GroupLayout(pnlDatosCuenta);
        pnlDatosCuenta.setLayout(pnlDatosCuentaLayout);
        pnlDatosCuentaLayout.setHorizontalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSaldoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatosCuentaLayout.createSequentialGroup()
                                    .addComponent(lblSignoDinero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblSaldoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(btnTransferir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(pnlCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarCuenta)))
                .addContainerGap())
        );
        pnlDatosCuentaLayout.setVerticalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                        .addComponent(lblSaldoDisponible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSignoDinero)
                            .addComponent(lblSaldoCuenta))
                        .addGap(18, 18, 18)
                        .addComponent(btnTransferir))
                    .addComponent(pnlCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnAgregarCuenta)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreCliente))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHola)
                    .addComponent(lblNombreCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlBanner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBanner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        CuentaDTO cuentaSeleccionada = seleccionarCuenta();
        if (cuentaSeleccionada != null) {
            controlador.irATransferencias(cuentaSeleccionada);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Hubo un error al recuperar la cuenta.");
        }
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void btnDatosCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosCuentaActionPerformed
        CuentaDTO cuentaSeleccionada = seleccionarCuenta();
        if (cuentaSeleccionada != null) {
            controlador.abrirCuentaDatos(cuentaSeleccionada);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Hubo un error al recuperar la cuenta.");
        }
    }//GEN-LAST:event_btnDatosCuentaActionPerformed

    private void btnAgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCuentaActionPerformed
        controlador.abrirCrearNuevaCuenta(cliente);
        this.dispose();
    }//GEN-LAST:event_btnAgregarCuentaActionPerformed

    private void cbxCuentasUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCuentasUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCuentasUsuarioActionPerformed

    private void btnOperaciones11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperaciones11ActionPerformed
        controlador.abrirHistorial();
        this.dispose();
    }//GEN-LAST:event_btnOperaciones11ActionPerformed

    private void btnPaginaCuenta22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuenta22ActionPerformed
        controlador.loginExitoso(cliente);
        this.dispose();
    }//GEN-LAST:event_btnPaginaCuenta22ActionPerformed

    private void btnEditarDatos11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatos11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarDatos11ActionPerformed

    private void btnPaginaCuenta23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuenta23ActionPerformed
        controlador.abrirInicioCliente(cliente);
        this.dispose();
    }//GEN-LAST:event_btnPaginaCuenta23ActionPerformed

    private CuentaDTO seleccionarCuenta() {
        Object seleccionado = cbxCuentasUsuario.getSelectedItem();
        if (seleccionado == null || seleccionado.toString().equals("No tiene cuentas aún")) { 
            JOptionPane.showMessageDialog(this, "Seleccione una cuenta válida");
            return null;
        }
        String numeroCuentaSeleccionada = seleccionado.toString();
        return controlador.obtenerCuentaPorNumero(numeroCuentaSeleccionada);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCuenta;
    private javax.swing.JButton btnDatosCuenta;
    private javax.swing.JButton btnEditarDatos;
    private javax.swing.JButton btnEditarDatos1;
    private javax.swing.JButton btnEditarDatos10;
    private javax.swing.JButton btnEditarDatos11;
    private javax.swing.JButton btnEditarDatos2;
    private javax.swing.JButton btnEditarDatos3;
    private javax.swing.JButton btnEditarDatos4;
    private javax.swing.JButton btnEditarDatos5;
    private javax.swing.JButton btnEditarDatos6;
    private javax.swing.JButton btnEditarDatos7;
    private javax.swing.JButton btnEditarDatos8;
    private javax.swing.JButton btnEditarDatos9;
    private javax.swing.JButton btnOperaciones;
    private javax.swing.JButton btnOperaciones1;
    private javax.swing.JButton btnOperaciones10;
    private javax.swing.JButton btnOperaciones11;
    private javax.swing.JButton btnOperaciones2;
    private javax.swing.JButton btnOperaciones3;
    private javax.swing.JButton btnOperaciones4;
    private javax.swing.JButton btnOperaciones5;
    private javax.swing.JButton btnOperaciones6;
    private javax.swing.JButton btnOperaciones7;
    private javax.swing.JButton btnOperaciones8;
    private javax.swing.JButton btnOperaciones9;
    private javax.swing.JButton btnPaginaCuenta;
    private javax.swing.JButton btnPaginaCuenta1;
    private javax.swing.JButton btnPaginaCuenta10;
    private javax.swing.JButton btnPaginaCuenta11;
    private javax.swing.JButton btnPaginaCuenta12;
    private javax.swing.JButton btnPaginaCuenta13;
    private javax.swing.JButton btnPaginaCuenta14;
    private javax.swing.JButton btnPaginaCuenta15;
    private javax.swing.JButton btnPaginaCuenta16;
    private javax.swing.JButton btnPaginaCuenta17;
    private javax.swing.JButton btnPaginaCuenta18;
    private javax.swing.JButton btnPaginaCuenta19;
    private javax.swing.JButton btnPaginaCuenta2;
    private javax.swing.JButton btnPaginaCuenta20;
    private javax.swing.JButton btnPaginaCuenta21;
    private javax.swing.JButton btnPaginaCuenta22;
    private javax.swing.JButton btnPaginaCuenta23;
    private javax.swing.JButton btnPaginaCuenta3;
    private javax.swing.JButton btnPaginaCuenta4;
    private javax.swing.JButton btnPaginaCuenta5;
    private javax.swing.JButton btnPaginaCuenta6;
    private javax.swing.JButton btnPaginaCuenta7;
    private javax.swing.JButton btnPaginaCuenta8;
    private javax.swing.JButton btnPaginaCuenta9;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JComboBox<String> cbxCuentasUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHola;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNumCuenta;
    private javax.swing.JLabel lblSaldoCuenta;
    private javax.swing.JLabel lblSaldoDisponible;
    private javax.swing.JLabel lblSignoDinero;
    private javax.swing.JPanel pnlBanner1;
    private javax.swing.JPanel pnlBanner10;
    private javax.swing.JPanel pnlBanner11;
    private javax.swing.JPanel pnlBanner12;
    private javax.swing.JPanel pnlBanner2;
    private javax.swing.JPanel pnlBanner3;
    private javax.swing.JPanel pnlBanner4;
    private javax.swing.JPanel pnlBanner5;
    private javax.swing.JPanel pnlBanner6;
    private javax.swing.JPanel pnlBanner7;
    private javax.swing.JPanel pnlBanner8;
    private javax.swing.JPanel pnlBanner9;
    private javax.swing.JPanel pnlCuentas;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatosCuenta;
    // End of variables declaration//GEN-END:variables
}
