/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.banco.presentacion;

import javax.swing.JOptionPane;
import org.itson.banco.dtos.ClienteDTO;
import org.itson.banco.dtos.CuentaDTO;
import org.itson.banco.dtos.RetiroDTO;
import org.itson.banco.negocio.NegocioException;
import org.itson.banco.negocio.RetiroBO;

/**
 *
 * @author oliro
 */
public class GenerarRetiroSinCuentaFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GenerarRetiroSinCuentaFORM.class.getName());

    private final ControladorTransferencia controlador;
    private final ClienteDTO clienteLogueado;
    private final CuentaDTO cuentaSeleccionada;
    
    private final RetiroBO retiroBO;
    
    /**
     * Creates new form GenrarRetiroSinCuentaFORM
     */
    public GenerarRetiroSinCuentaFORM(ControladorTransferencia controlador, ClienteDTO cliente, CuentaDTO cuenta) {
        this.controlador = controlador;
        this.clienteLogueado = cliente;
        this.cuentaSeleccionada = cuenta;
        this.retiroBO = new RetiroBO();
        initComponents();
        cargarDatos();
    }
    
    private void cargarDatos() {
        lblNoCuenta.setText(cuentaSeleccionada.getNumeroCuenta());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlFondo2 = new javax.swing.JPanel();
        pnlFondo3 = new javax.swing.JPanel();
        pnlCuenta = new javax.swing.JPanel();
        lblTextNoCuenta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNoCuenta = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        pnlBanner1 = new javax.swing.JPanel();
        btnOperaciones = new javax.swing.JButton();
        btnPaginaCuenta = new javax.swing.JButton();
        btnEditarDatos = new javax.swing.JButton();
        btnPaginaCuenta1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generar retiro sin cuenta");
        setPreferredSize(new java.awt.Dimension(600, 450));

        pnlFondo.setBackground(new java.awt.Color(245, 239, 235));
        pnlFondo.setForeground(new java.awt.Color(245, 239, 235));

        pnlFondo2.setBackground(new java.awt.Color(217, 217, 217));
        pnlFondo2.setForeground(new java.awt.Color(217, 217, 217));

        pnlFondo3.setBackground(new java.awt.Color(255, 255, 255));

        pnlCuenta.setBackground(new java.awt.Color(200, 217, 230));

        lblTextNoCuenta.setBackground(new java.awt.Color(0, 0, 0));
        lblTextNoCuenta.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblTextNoCuenta.setText("No. Cuenta");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("VOYAGE");

        lblNoCuenta.setBackground(new java.awt.Color(0, 0, 0));
        lblNoCuenta.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblNoCuenta.setText("*** *** *** ****");

        javax.swing.GroupLayout pnlCuentaLayout = new javax.swing.GroupLayout(pnlCuenta);
        pnlCuenta.setLayout(pnlCuentaLayout);
        pnlCuentaLayout.setHorizontalGroup(
            pnlCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCuentaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCuentaLayout.createSequentialGroup()
                        .addComponent(lblTextNoCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(lblNoCuenta)))
                .addContainerGap())
        );
        pnlCuentaLayout.setVerticalGroup(
            pnlCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextNoCuenta)
                    .addComponent(lblNoCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnVolver.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel1.setText("Monto");

        btnGenerar.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(this::btnGenerarActionPerformed);

        javax.swing.GroupLayout pnlFondo3Layout = new javax.swing.GroupLayout(pnlFondo3);
        pnlFondo3.setLayout(pnlFondo3Layout);
        pnlFondo3Layout.setHorizontalGroup(
            pnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondo3Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(pnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondo3Layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondo3Layout.createSequentialGroup()
                        .addComponent(pnlCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondo3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondo3Layout.createSequentialGroup()
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondo3Layout.createSequentialGroup()
                        .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );
        pnlFondo3Layout.setVerticalGroup(
            pnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondo3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerar)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFondo2Layout = new javax.swing.GroupLayout(pnlFondo2);
        pnlFondo2.setLayout(pnlFondo2Layout);
        pnlFondo2Layout.setHorizontalGroup(
            pnlFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFondo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFondo2Layout.setVerticalGroup(
            pnlFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFondo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBanner1.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanner1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlBanner1.setAlignmentY(0.0F);

        btnOperaciones.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnOperaciones.setText("Operaciones");
        btnOperaciones.setToolTipText("");
        btnOperaciones.setBorder(null);
        btnOperaciones.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnOperaciones.addActionListener(this::btnOperacionesActionPerformed);

        btnPaginaCuenta.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnPaginaCuenta.setText("Cuentas");
        btnPaginaCuenta.setToolTipText("");
        btnPaginaCuenta.setBorder(null);
        btnPaginaCuenta.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta.addActionListener(this::btnPaginaCuentaActionPerformed);

        btnEditarDatos.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnEditarDatos.setText("Perfil");
        btnEditarDatos.setToolTipText("");
        btnEditarDatos.setBorder(null);
        btnEditarDatos.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnEditarDatos.addActionListener(this::btnEditarDatosActionPerformed);

        btnPaginaCuenta1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPaginaCuenta1.setText("VOYAGE");
        btnPaginaCuenta1.setToolTipText("");
        btnPaginaCuenta1.setBorder(null);
        btnPaginaCuenta1.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta1.addActionListener(this::btnPaginaCuenta1ActionPerformed);

        javax.swing.GroupLayout pnlBanner1Layout = new javax.swing.GroupLayout(pnlBanner1);
        pnlBanner1.setLayout(pnlBanner1Layout);
        pnlBanner1Layout.setHorizontalGroup(
            pnlBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnPaginaCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnPaginaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnEditarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        pnlBanner1Layout.setVerticalGroup(
            pnlBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner1Layout.createSequentialGroup()
                .addGroup(pnlBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaginaCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaginaCuenta)
                    .addComponent(btnOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBanner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(pnlFondo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBanner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFondo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        controlador.loginExitoso(clienteLogueado);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        
        String montoString = txtMonto.getText();
        
        double monto = 0;
        
        try{
            monto = Double.parseDouble(montoString);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Monto invalido.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        try {
            RetiroDTO retiroDTO = retiroBO.generarRetiroSinCuenta(cuentaSeleccionada.getNumeroCuenta(), monto);
            controlador.abrirRetiroSinCuentaGeneradoExitoFORM(retiroDTO);
            dispose();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        
        
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacionesActionPerformed
        controlador.abrirHistorial();
        this.dispose();
    }//GEN-LAST:event_btnOperacionesActionPerformed

    private void btnPaginaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuentaActionPerformed
        controlador.loginExitoso(clienteLogueado);
        this.dispose();
    }//GEN-LAST:event_btnPaginaCuentaActionPerformed

    private void btnEditarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarDatosActionPerformed

    private void btnPaginaCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuenta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaginaCuenta1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarDatos;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnOperaciones;
    private javax.swing.JButton btnPaginaCuenta;
    private javax.swing.JButton btnPaginaCuenta1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNoCuenta;
    private javax.swing.JLabel lblTextNoCuenta;
    private javax.swing.JPanel pnlBanner1;
    private javax.swing.JPanel pnlCuenta;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlFondo2;
    private javax.swing.JPanel pnlFondo3;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
