/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.banco.presentacion;

import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.itson.banco.dtos.ClienteDTO;

/**
 *
 * @author emyla
 */
public class InicioClienteFORM extends javax.swing.JFrame {

    private static final Logger LOGGER = Logger.getLogger(InicioClienteFORM.class.getName());
    private ControladorTransferencia controlador;
    private ClienteDTO cliente;
    /**
     * Creates new form InicioCliente
     */
    public InicioClienteFORM(ControladorTransferencia controlador, ClienteDTO cliente) {
        this.controlador = controlador;
        this.cliente = cliente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        scbScroll = new javax.swing.JScrollBar();
        pnlBanner1 = new javax.swing.JPanel();
        lblVoyage1 = new javax.swing.JLabel();
        btnOperaciones = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        lblIcono = new javax.swing.JLabel();
        btnPaginaCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 239, 235));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("BANCO VOYAGE");

        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(245, 239, 235));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed vulputate purus, nec congue \nmetus. In quis euismod dui, iaculis fringilla mi. Cras dignissim lorem at consectetur laoreet. Curabitur \net mattis sapien. Nulla feugiat id enim non semper. Vestibulum erat tortor, viverra nec posuere in, \ngravida et ligula. Etiam pulvinar, arcu et dignissim venenatis, felis libero vehicula mi, ac hendrerit \nligula lectus eget justo. Vivamus tempor libero ac ante accumsan ultrices. Aliquam ultrices, augue \ngravida malesuada lacinia, tortor metus luctus sem, nec molestie ipsum magna nec arcu. Donec \naugue nibh, tincidunt vel risus vitae, aliquet auctor lacus. Praesent maximus orci eleifend lacus \nfinibus ");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        pnlBanner1.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanner1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlBanner1.setAlignmentY(0.0F);

        lblVoyage1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblVoyage1.setText("VOYAGE");

        btnOperaciones.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnOperaciones.setText("Operaciones");
        btnOperaciones.setToolTipText("");
        btnOperaciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOperaciones.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacionesActionPerformed(evt);
            }
        });

        btnAyuda.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnAyuda.setText("Ayuda");
        btnAyuda.setToolTipText("");
        btnAyuda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAyuda.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        lblIcono.setBackground(new java.awt.Color(255, 255, 255));
        lblIcono.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        lblIcono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIcono.setText("Usuario...");
        lblIcono.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnPaginaCuenta.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnPaginaCuenta.setText("Cuentas");
        btnPaginaCuenta.setToolTipText("");
        btnPaginaCuenta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPaginaCuenta.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBanner1Layout = new javax.swing.GroupLayout(pnlBanner1);
        pnlBanner1.setLayout(pnlBanner1Layout);
        pnlBanner1Layout.setHorizontalGroup(
            pnlBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblVoyage1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnPaginaCuenta)
                .addGap(45, 45, 45)
                .addComponent(btnOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        pnlBanner1Layout.setVerticalGroup(
            pnlBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblVoyage1)
                .addComponent(btnOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIcono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPaginaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBanner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(scbScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pnlBanner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 116, Short.MAX_VALUE))
            .addComponent(scbScroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        JOptionPane.showMessageDialog(this, "Chamba quien sabe, hay q checar eso");
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacionesActionPerformed
        JOptionPane.showMessageDialog(this, "Chamba Nafi");
    }//GEN-LAST:event_btnOperacionesActionPerformed

    private void btnPaginaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuentaActionPerformed
        controlador.loginExitoso(cliente);
        this.dispose();
    }//GEN-LAST:event_btnPaginaCuentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnOperaciones;
    private javax.swing.JButton btnPaginaCuenta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblVoyage1;
    private javax.swing.JPanel pnlBanner1;
    private javax.swing.JScrollBar scbScroll;
    // End of variables declaration//GEN-END:variables
}
