/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.banco.presentacion;

import java.util.GregorianCalendar;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.itson.banco.dtos.ClienteDTO;
import org.itson.banco.dtos.CuentaDTO;
import org.itson.banco.negocio.CuentaBO;
import org.itson.banco.negocio.ICuentaBO;
import org.itson.banco.negocio.NegocioException;
import org.itson.banco.persistencia.ConexionBD;
import org.itson.banco.persistencia.CuentaDAO;

/**
 *
 * @author emyla
 */
public class NuevaCuentaFORM extends javax.swing.JFrame {

    private static final Logger LOGGER = Logger.getLogger(NuevaCuentaFORM.class.getName());
    private ControladorTransferencia controlador;
    private ClienteDTO cliente;
    private CuentaBO cuentaBO;
    /**
     * Creates new form NuevaCuentaFORM
     */
    public NuevaCuentaFORM(ControladorTransferencia controlador, ClienteDTO cliente) {
        this.controlador = controlador;
        this.cliente = cliente;
        this.cuentaBO = new CuentaBO(new CuentaDAO(new ConexionBD()));
        setLocationRelativeTo(null);
        initComponents();
        cargarNombreCompleto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        pnlDatosCuenta = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        txtClienteAsociado = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        lblCuentaOrigen2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblApellidoPat = new javax.swing.JLabel();
        txtApellidoPat = new javax.swing.JTextField();
        lblApellidoMat = new javax.swing.JLabel();
        txtApellidoMat = new javax.swing.JTextField();
        lblTitulo1 = new javax.swing.JLabel();
        btnVolver1 = new javax.swing.JButton();
        pnlBanner2 = new javax.swing.JPanel();
        btnPaginaCuenta1 = new javax.swing.JButton();
        lblVoyage1 = new javax.swing.JLabel();
        lblIcono1 = new javax.swing.JLabel();
        btnAyuda1 = new javax.swing.JButton();
        btnOperaciones1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear cuenta nueva");

        pnlDatos.setBackground(new java.awt.Color(217, 217, 217));

        pnlDatosCuenta.setBackground(new java.awt.Color(255, 255, 255));

        lblNombre.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");

        btnContinuar.setBackground(new java.awt.Color(200, 217, 230));
        btnContinuar.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Agregar Nueva Cuenta");
        lblTitulo.setToolTipText("");

        txtClienteAsociado.setEditable(false);
        txtClienteAsociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteAsociadoActionPerformed(evt);
            }
        });

        lblCuentaOrigen2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblCuentaOrigen2.setText("Monto");

        btnVolver.setText("Cancelar");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblApellidoPat.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblApellidoPat.setText("Apellido Paterno");

        txtApellidoPat.setEditable(false);
        txtApellidoPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPatActionPerformed(evt);
            }
        });

        lblApellidoMat.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblApellidoMat.setText("Apellido Materno");

        txtApellidoMat.setEditable(false);
        txtApellidoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMatActionPerformed(evt);
            }
        });

        lblTitulo1.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("Si crees que hay un error en tus datos, has click AQUÍ para editar datos personales.");

        btnVolver1.setText("Editar mis datos");
        btnVolver1.setToolTipText("");
        btnVolver1.setBorder(null);
        btnVolver1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosCuentaLayout = new javax.swing.GroupLayout(pnlDatosCuenta);
        pnlDatosCuenta.setLayout(pnlDatosCuentaLayout);
        pnlDatosCuentaLayout.setHorizontalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(188, 188, 188))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                                .addComponent(btnVolver1)
                                .addGap(195, 195, 195))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addGap(201, 201, 201))))
                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtClienteAsociado, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtApellidoPat)
                                            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                                                .addComponent(lblApellidoPat, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                                        .addComponent(lblApellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtApellidoMat)))
                            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCuentaOrigen2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        pnlDatosCuentaLayout.setVerticalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitulo)
                .addGap(42, 42, 42)
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblApellidoPat)
                    .addComponent(lblApellidoMat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteAsociado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCuentaOrigen2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnContinuar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver1)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnlBanner2.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanner2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlBanner2.setAlignmentY(0.0F);

        btnPaginaCuenta1.setBackground(new java.awt.Color(86, 124, 141));
        btnPaginaCuenta1.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnPaginaCuenta1.setForeground(new java.awt.Color(255, 255, 255));
        btnPaginaCuenta1.setText("Cuentas");
        btnPaginaCuenta1.setToolTipText("");
        btnPaginaCuenta1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPaginaCuenta1.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaCuenta1ActionPerformed(evt);
            }
        });

        lblVoyage1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblVoyage1.setText("VOYAGE");

        lblIcono1.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        lblIcono1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIcono1.setText("Usuario...");

        btnAyuda1.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnAyuda1.setText("Ayuda");
        btnAyuda1.setToolTipText("");
        btnAyuda1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAyuda1.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnAyuda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyuda1ActionPerformed(evt);
            }
        });

        btnOperaciones1.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnOperaciones1.setText("Operaciones");
        btnOperaciones1.setToolTipText("");
        btnOperaciones1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOperaciones1.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnOperaciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperaciones1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBanner2Layout = new javax.swing.GroupLayout(pnlBanner2);
        pnlBanner2.setLayout(pnlBanner2Layout);
        pnlBanner2Layout.setHorizontalGroup(
            pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblVoyage1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPaginaCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOperaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnAyuda1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lblIcono1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        pnlBanner2Layout.setVerticalGroup(
            pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnPaginaCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblVoyage1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBanner2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOperaciones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAyuda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIcono1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(pnlBanner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(pnlBanner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        confirmar();

    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * Método privado de confirmar. Este método se activa una vez el usuario confirme que quiere crear su cuenta
     */
    private void confirmar() {

        try {
            String montoString = txtMonto.getText();

            if (montoString.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un monto");
                return;
            }

            double monto;
            try {
                monto = Double.parseDouble(montoString);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Monto inválido");
                return;
            }

            if (monto <= 0) {
                JOptionPane.showMessageDialog(this, "El monto debe ser mayor a $0");
                return;
            }

            CuentaDTO cuentaDTO = new CuentaDTO();
            cuentaDTO.setSaldoCuenta(monto);
            cuentaDTO.setEstado("activa");
            cuentaDTO.setFechaApertura(new GregorianCalendar());

            cuentaBO.crearNuevaCuenta(cuentaDTO, cliente.getId());

            controlador.abrirCreacionCuentaExitosa(cliente, cuentaDTO);
            this.dispose();

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Error al crear cuenta",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de querer volver?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            // Acción si el usuario dice SÍ
            controlador.loginExitoso(cliente);
            this.dispose(); // cerrar ventana actual
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtClienteAsociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteAsociadoActionPerformed
        cargarCliente();
    }//GEN-LAST:event_txtClienteAsociadoActionPerformed

    private void txtApellidoPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPatActionPerformed
        cargarApellidoP();
    }//GEN-LAST:event_txtApellidoPatActionPerformed

    private void txtApellidoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMatActionPerformed
        cargarApellidoM();
    }//GEN-LAST:event_txtApellidoMatActionPerformed

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        JOptionPane.showMessageDialog(null, "Chamba Emy para más adelante");
    }//GEN-LAST:event_btnVolver1ActionPerformed

    private void btnPaginaCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuenta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaginaCuenta1ActionPerformed

    private void btnAyuda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyuda1ActionPerformed
        JOptionPane.showMessageDialog(this, "Chamba quien sabe, hay q checar eso");
    }//GEN-LAST:event_btnAyuda1ActionPerformed

    private void btnOperaciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperaciones1ActionPerformed
        JOptionPane.showMessageDialog(this, "Chamba Nafi");
    }//GEN-LAST:event_btnOperaciones1ActionPerformed

    private void cargarCliente(){
        txtClienteAsociado.setText(String.valueOf(cliente.getNombres()));
    }
    
    private void cargarApellidoP(){
        txtApellidoPat.setText(String.valueOf(cliente.getApellidoPaterno()));
    }
    
    private void cargarApellidoM(){
        txtApellidoMat.setText(String.valueOf(cliente.getApellidoMaterno()));
    }

    /** 
     * Mexicanada q me rifé para mandar a llamar todos los "cargar..." para que los datos se carguen 
     * automaticamente en las partes que les toca :3
     */
    private void cargarNombreCompleto(){
        cargarCliente();
        cargarApellidoP();
        cargarApellidoM();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda1;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnOperaciones1;
    private javax.swing.JButton btnPaginaCuenta1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JLabel lblApellidoMat;
    private javax.swing.JLabel lblApellidoPat;
    private javax.swing.JLabel lblCuentaOrigen2;
    private javax.swing.JLabel lblIcono1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblVoyage1;
    private javax.swing.JPanel pnlBanner2;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatosCuenta;
    private javax.swing.JTextField txtApellidoMat;
    private javax.swing.JTextField txtApellidoPat;
    private javax.swing.JTextField txtClienteAsociado;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
