/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.banco.presentacion;

import java.util.GregorianCalendar;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.itson.banco.dtos.ClienteDTO;
import org.itson.banco.dtos.CuentaDTO;
import org.itson.banco.negocio.CuentaBO;
import org.itson.banco.negocio.ICuentaBO;
import org.itson.banco.negocio.NegocioException;
import org.itson.banco.persistencia.ConexionBD;
import org.itson.banco.persistencia.CuentaDAO;

/**
 *
 * @author emyla
 */
public class NuevaCuentaFORM extends javax.swing.JFrame {

    private static final Logger LOGGER = Logger.getLogger(NuevaCuentaFORM.class.getName());
    private final ControladorTransferencia controlador;
    private final ClienteDTO cliente;
    private final CuentaBO cuentaBO;

    public NuevaCuentaFORM(
        ControladorTransferencia controlador,
        ClienteDTO cliente,
        CuentaBO cuentaBO
    ) {
        this.controlador = controlador;
        this.cliente = cliente;
        this.cuentaBO = cuentaBO;

        initComponents();
        setLocationRelativeTo(null);
        cargarNombreCompleto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        pnlDatosCuenta = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        txtClienteAsociado = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        lblCuentaOrigen2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblApellidoPat = new javax.swing.JLabel();
        txtApellidoPat = new javax.swing.JTextField();
        lblApellidoMat = new javax.swing.JLabel();
        txtApellidoMat = new javax.swing.JTextField();
        pnlBanner1 = new javax.swing.JPanel();
        btnOperaciones = new javax.swing.JButton();
        btnPaginaCuenta = new javax.swing.JButton();
        btnEditarDatos = new javax.swing.JButton();
        btnPaginaCuenta1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear cuenta nueva");

        pnlDatos.setBackground(new java.awt.Color(217, 217, 217));
        pnlDatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlDatosCuenta.setBackground(new java.awt.Color(255, 255, 255));

        lblNombre.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");

        btnContinuar.setBackground(new java.awt.Color(200, 217, 230));
        btnContinuar.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Agregar Nueva Cuenta");
        lblTitulo.setToolTipText("");

        txtClienteAsociado.setEditable(false);
        txtClienteAsociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteAsociadoActionPerformed(evt);
            }
        });

        lblCuentaOrigen2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblCuentaOrigen2.setText("Monto");

        btnVolver.setText("Cancelar");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblApellidoPat.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblApellidoPat.setText("Apellido Paterno");

        txtApellidoPat.setEditable(false);
        txtApellidoPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPatActionPerformed(evt);
            }
        });

        lblApellidoMat.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblApellidoMat.setText("Apellido Materno");

        txtApellidoMat.setEditable(false);
        txtApellidoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosCuentaLayout = new javax.swing.GroupLayout(pnlDatosCuenta);
        pnlDatosCuenta.setLayout(pnlDatosCuentaLayout);
        pnlDatosCuentaLayout.setHorizontalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClienteAsociado, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidoPat)
                                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblApellidoPat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 4, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                                .addComponent(lblApellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 4, Short.MAX_VALUE))
                            .addComponent(txtApellidoMat)))
                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCuentaOrigen2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(219, 219, 219))
        );
        pnlDatosCuentaLayout.setVerticalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblApellidoPat)
                    .addComponent(lblApellidoMat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteAsociado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCuentaOrigen2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnContinuar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBanner1.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanner1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlBanner1.setAlignmentY(0.0F);

        btnOperaciones.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnOperaciones.setText("Operaciones");
        btnOperaciones.setToolTipText("");
        btnOperaciones.setBorder(null);
        btnOperaciones.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacionesActionPerformed(evt);
            }
        });

        btnPaginaCuenta.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnPaginaCuenta.setText("Cuentas");
        btnPaginaCuenta.setToolTipText("");
        btnPaginaCuenta.setBorder(null);
        btnPaginaCuenta.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaCuentaActionPerformed(evt);
            }
        });

        btnEditarDatos.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnEditarDatos.setText("Perfil");
        btnEditarDatos.setToolTipText("");
        btnEditarDatos.setBorder(null);
        btnEditarDatos.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnEditarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDatosActionPerformed(evt);
            }
        });

        btnPaginaCuenta1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPaginaCuenta1.setText("VOYAGE");
        btnPaginaCuenta1.setToolTipText("");
        btnPaginaCuenta1.setBorder(null);
        btnPaginaCuenta1.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaCuenta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBanner1Layout = new javax.swing.GroupLayout(pnlBanner1);
        pnlBanner1.setLayout(pnlBanner1Layout);
        pnlBanner1Layout.setHorizontalGroup(
            pnlBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnPaginaCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPaginaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnEditarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        pnlBanner1Layout.setVerticalGroup(
            pnlBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner1Layout.createSequentialGroup()
                .addGroup(pnlBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaginaCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaginaCuenta)
                    .addComponent(btnOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBanner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBanner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        confirmar();

    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * Método privado de confirmar. Este método se activa una vez el usuario confirme que quiere crear su cuenta
     */
    private void confirmar() {

        try {
            String montoString = txtMonto.getText();

            if (montoString.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un monto");
                return;
            }

            double monto;
            try {
                monto = Double.parseDouble(montoString);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Monto inválido");
                return;
            }

            if (monto <= 0) {
                JOptionPane.showMessageDialog(this, "El monto debe ser mayor a $0");
                return;
            }

            CuentaDTO cuentaDTO = new CuentaDTO();
            cuentaDTO.setSaldoCuenta(monto);
            cuentaDTO.setEstado("activa");
            cuentaDTO.setFechaApertura(new GregorianCalendar());

            cuentaBO.crearNuevaCuenta(cuentaDTO, cliente.getId());

            controlador.abrirCreacionCuentaExitosa(cliente, cuentaDTO);
            this.dispose();

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Error al crear cuenta",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de querer volver?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            // Acción si el usuario dice SÍ
            controlador.loginExitoso(cliente);
            this.dispose(); // cerrar ventana actual
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtClienteAsociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteAsociadoActionPerformed
        cargarCliente();
    }//GEN-LAST:event_txtClienteAsociadoActionPerformed

    private void txtApellidoPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPatActionPerformed
        cargarApellidoP();
    }//GEN-LAST:event_txtApellidoPatActionPerformed

    private void txtApellidoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMatActionPerformed
        cargarApellidoM();
    }//GEN-LAST:event_txtApellidoMatActionPerformed

    private void btnOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacionesActionPerformed
        controlador.abrirHistorial();
        this.dispose();
    }//GEN-LAST:event_btnOperacionesActionPerformed

    private void btnPaginaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuentaActionPerformed
        controlador.loginExitoso(cliente);
        this.dispose();
    }//GEN-LAST:event_btnPaginaCuentaActionPerformed

    private void btnEditarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarDatosActionPerformed

    private void btnPaginaCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuenta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaginaCuenta1ActionPerformed

    private void cargarCliente(){
        txtClienteAsociado.setText(String.valueOf(cliente.getNombres()));
    }
    
    private void cargarApellidoP(){
        txtApellidoPat.setText(String.valueOf(cliente.getApellidoPaterno()));
    }
    
    private void cargarApellidoM(){
        txtApellidoMat.setText(String.valueOf(cliente.getApellidoMaterno()));
    }

    /** 
     * Mexicanada q me rifé para mandar a llamar todos los "cargar..." para que los datos se carguen 
     * automaticamente en las partes que les toca :3
     */
    private void cargarNombreCompleto(){
        cargarCliente();
        cargarApellidoP();
        cargarApellidoM();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnEditarDatos;
    private javax.swing.JButton btnOperaciones;
    private javax.swing.JButton btnPaginaCuenta;
    private javax.swing.JButton btnPaginaCuenta1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblApellidoMat;
    private javax.swing.JLabel lblApellidoPat;
    private javax.swing.JLabel lblCuentaOrigen2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBanner1;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatosCuenta;
    private javax.swing.JTextField txtApellidoMat;
    private javax.swing.JTextField txtApellidoPat;
    private javax.swing.JTextField txtClienteAsociado;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
