/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.banco.presentacion;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import org.itson.banco.dtos.ClienteDTO;
import org.itson.banco.dtos.DireccionDTO;

/**
 *
 * @author emyla
 */
public class PerfilUsuarioFORM extends javax.swing.JFrame {

    private ControladorTransferencia controlador;
    private ClienteDTO clienteLogueado;
    /**
     * Creates new form PerfilUsuarioFORM
     */
    public PerfilUsuarioFORM(ControladorTransferencia controlador, ClienteDTO clienteLogueado) {
        this.clienteLogueado = clienteLogueado;
        this.controlador = controlador;
        initComponents();
        cargarDatosCliente();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        pnlBanner12 = new javax.swing.JPanel();
        btnOperaciones11 = new javax.swing.JButton();
        btnPaginaCuenta22 = new javax.swing.JButton();
        btnEditarDatos11 = new javax.swing.JButton();
        btnPaginaCuenta23 = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        lblHola = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblHola1 = new javax.swing.JLabel();
        lblHola2 = new javax.swing.JLabel();
        lblApellidoPat = new javax.swing.JLabel();
        lblApellidoMat = new javax.swing.JLabel();
        lblHola3 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHola4 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblHola5 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 239, 235));

        btnVolver.setBackground(new java.awt.Color(245, 239, 235));
        btnVolver.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        pnlBanner12.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanner12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlBanner12.setAlignmentY(0.0F);

        btnOperaciones11.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnOperaciones11.setText("Operaciones");
        btnOperaciones11.setToolTipText("");
        btnOperaciones11.setBorder(null);
        btnOperaciones11.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnOperaciones11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperaciones11ActionPerformed(evt);
            }
        });

        btnPaginaCuenta22.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnPaginaCuenta22.setText("Cuentas");
        btnPaginaCuenta22.setToolTipText("");
        btnPaginaCuenta22.setBorder(null);
        btnPaginaCuenta22.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaCuenta22ActionPerformed(evt);
            }
        });

        btnEditarDatos11.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnEditarDatos11.setText("Perfil");
        btnEditarDatos11.setToolTipText("");
        btnEditarDatos11.setBorder(null);
        btnEditarDatos11.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnEditarDatos11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDatos11ActionPerformed(evt);
            }
        });

        btnPaginaCuenta23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPaginaCuenta23.setText("VOYAGE");
        btnPaginaCuenta23.setToolTipText("");
        btnPaginaCuenta23.setBorder(null);
        btnPaginaCuenta23.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaCuenta23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBanner12Layout = new javax.swing.GroupLayout(pnlBanner12);
        pnlBanner12.setLayout(pnlBanner12Layout);
        pnlBanner12Layout.setHorizontalGroup(
            pnlBanner12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner12Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnPaginaCuenta23, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnPaginaCuenta22, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnOperaciones11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnEditarDatos11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        pnlBanner12Layout.setVerticalGroup(
            pnlBanner12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner12Layout.createSequentialGroup()
                .addGroup(pnlBanner12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaginaCuenta23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaginaCuenta22)
                    .addComponent(btnOperaciones11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarDatos11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlDatos.setBackground(new java.awt.Color(255, 255, 255));

        lblHola.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        lblHola.setText("Nombre");

        lblNombre.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblNombre.setText("nombre");

        lblHola1.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        lblHola1.setText("Apellido paterno");

        lblHola2.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        lblHola2.setText("Apellido materno");

        lblApellidoPat.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblApellidoPat.setText("apellidoP");

        lblApellidoMat.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblApellidoMat.setText("apellidoM");

        lblHola3.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        lblHola3.setText("Fecha de nacimiento");

        lblFecha.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblFecha.setText("fechaNac");

        lblHola4.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        lblHola4.setText("Dirección");

        lblDireccion.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblDireccion.setText("direccion");

        lblHola5.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        lblHola5.setText("Correo");

        lblCorreo.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblCorreo.setText("correo");

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblHola)
                                    .addComponent(lblHola3, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDatosLayout.createSequentialGroup()
                                        .addComponent(lblHola4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57))
                                    .addGroup(pnlDatosLayout.createSequentialGroup()
                                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblHola1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblApellidoPat, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addComponent(lblHola5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(225, 225, 225)))
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHola2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHola)
                    .addComponent(lblHola1)
                    .addComponent(lblHola2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblApellidoPat)
                    .addComponent(lblApellidoMat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHola3)
                    .addComponent(lblHola4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(lblDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHola5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorreo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCerrarSesion.setBackground(new java.awt.Color(255, 102, 102));
        btnCerrarSesion.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlBanner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBanner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrarSesion)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOperaciones11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperaciones11ActionPerformed
        this.dispose();
        controlador.abrirHistorial();
    }//GEN-LAST:event_btnOperaciones11ActionPerformed

    private void btnPaginaCuenta22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuenta22ActionPerformed
        this.dispose();
        controlador.loginExitoso(clienteLogueado);
    }//GEN-LAST:event_btnPaginaCuenta22ActionPerformed

    private void btnEditarDatos11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatos11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarDatos11ActionPerformed

    private void btnPaginaCuenta23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuenta23ActionPerformed
        this.dispose();
        controlador.abrirInicioCliente(clienteLogueado);
    }//GEN-LAST:event_btnPaginaCuenta23ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de querer volver?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            // Acción si el usuario dice SÍ
            controlador.loginExitoso(clienteLogueado);
            this.dispose(); // cerrar ventana actual
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de que desea cerrar sesión?",
            "Confirmar cierre de sesión",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
            controlador.cerrarSesion();
            JOptionPane.showMessageDialog(
                null,
                "Sesión cerrada correctamente. ¡Hasta pronto!",
                "Sesión cerrada",
                JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void cargarDatosCliente() {
        lblNombre.setText(clienteLogueado.getNombres());
        lblApellidoPat.setText(clienteLogueado.getApellidoPaterno());
        lblApellidoMat.setText(clienteLogueado.getApellidoMaterno());

        if (clienteLogueado.getFechaNacimiento() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String fechaFormateada = sdf.format(
                clienteLogueado.getFechaNacimiento().getTime()
            );
            lblFecha.setText(fechaFormateada);
        } else {
            lblFecha.setText("No registrada");
        }

        lblCorreo.setText(clienteLogueado.getCorreo());

        // Mostrar dirección si existe
        if (clienteLogueado.getDireccion() != null) {
            DireccionDTO dir = clienteLogueado.getDireccion();
            String direccionCompleta = dir.getCalle() + " #" + dir.getNumero() + 
                                       ", " + dir.getColonia();
            lblDireccion.setText(direccionCompleta);
        } else {
            lblDireccion.setText("No registrada");
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEditarDatos11;
    private javax.swing.JButton btnOperaciones11;
    private javax.swing.JButton btnPaginaCuenta22;
    private javax.swing.JButton btnPaginaCuenta23;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidoMat;
    private javax.swing.JLabel lblApellidoPat;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHola;
    private javax.swing.JLabel lblHola1;
    private javax.swing.JLabel lblHola2;
    private javax.swing.JLabel lblHola3;
    private javax.swing.JLabel lblHola4;
    private javax.swing.JLabel lblHola5;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlBanner12;
    private javax.swing.JPanel pnlDatos;
    // End of variables declaration//GEN-END:variables
}
