/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.banco.presentacion;

import javax.swing.JOptionPane;
import org.itson.banco.dtos.ClienteDTO;

/**
 *
 * @author oliro
 */
public class TransferenciaExitosa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransferenciaExitosa.class.getName());
    private final ControladorTransferencia controlador;
    private final ClienteDTO cliente;
    private final int folio;

    /**
     * Creates new form TransferenciaExitosa
     */
    public TransferenciaExitosa(ControladorTransferencia controlador, ClienteDTO cliente, int folio) {
        this.controlador = controlador;
        this.cliente = cliente;
        this.folio = folio;
        initComponents();
        cargarDatos();
    }
    
    public void cargarDatos(){
        String folioString = String.valueOf(folio);
        lblFolio.setText(folioString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        pnlDatosCuenta = new javax.swing.JPanel();
        lblOperacionExitosa = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblFolioOperacion = new javax.swing.JLabel();
        lblFolio = new javax.swing.JLabel();
        pnlBanner3 = new javax.swing.JPanel();
        btnPaginaCuenta2 = new javax.swing.JButton();
        lblVoyage2 = new javax.swing.JLabel();
        lblIcono2 = new javax.swing.JLabel();
        btnAyuda2 = new javax.swing.JButton();
        btnOperaciones2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Éxito");

        pnlDatos.setBackground(new java.awt.Color(217, 217, 217));

        pnlDatosCuenta.setBackground(new java.awt.Color(255, 255, 255));

        lblOperacionExitosa.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lblOperacionExitosa.setText("Operacion éxitosa");

        btnVolver.setBackground(new java.awt.Color(47, 65, 86));
        btnVolver.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        lblFolioOperacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFolioOperacion.setText("Folio de operación");

        lblFolio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFolio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFolio.setText(".");

        javax.swing.GroupLayout pnlDatosCuentaLayout = new javax.swing.GroupLayout(pnlDatosCuenta);
        pnlDatosCuenta.setLayout(pnlDatosCuentaLayout);
        pnlDatosCuentaLayout.setHorizontalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                        .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblFolioOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFolio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                        .addComponent(lblOperacionExitosa)
                        .addGap(188, 188, 188))))
        );
        pnlDatosCuentaLayout.setVerticalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblOperacionExitosa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFolioOperacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFolio)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlBanner3.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanner3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlBanner3.setAlignmentY(0.0F);

        btnPaginaCuenta2.setBackground(new java.awt.Color(86, 124, 141));
        btnPaginaCuenta2.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnPaginaCuenta2.setForeground(new java.awt.Color(255, 255, 255));
        btnPaginaCuenta2.setText("Cuentas");
        btnPaginaCuenta2.setToolTipText("");
        btnPaginaCuenta2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPaginaCuenta2.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta2.addActionListener(this::btnPaginaCuenta2ActionPerformed);

        lblVoyage2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblVoyage2.setText("VOYAGE");

        lblIcono2.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        lblIcono2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIcono2.setText("Usuario...");

        btnAyuda2.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnAyuda2.setText("Ayuda");
        btnAyuda2.setToolTipText("");
        btnAyuda2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAyuda2.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnAyuda2.addActionListener(this::btnAyuda2ActionPerformed);

        btnOperaciones2.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnOperaciones2.setText("Operaciones");
        btnOperaciones2.setToolTipText("");
        btnOperaciones2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOperaciones2.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnOperaciones2.addActionListener(this::btnOperaciones2ActionPerformed);

        javax.swing.GroupLayout pnlBanner3Layout = new javax.swing.GroupLayout(pnlBanner3);
        pnlBanner3.setLayout(pnlBanner3Layout);
        pnlBanner3Layout.setHorizontalGroup(
            pnlBanner3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblVoyage2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPaginaCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOperaciones2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnAyuda2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lblIcono2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        pnlBanner3Layout.setVerticalGroup(
            pnlBanner3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnPaginaCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblVoyage2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBanner3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBanner3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOperaciones2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAyuda2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIcono2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBanner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(pnlBanner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        controlador.loginExitoso(cliente);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnPaginaCuenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuenta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaginaCuenta2ActionPerformed

    private void btnAyuda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyuda2ActionPerformed
        JOptionPane.showMessageDialog(this, "Chamba quien sabe, hay q checar eso");
    }//GEN-LAST:event_btnAyuda2ActionPerformed

    private void btnOperaciones2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperaciones2ActionPerformed
        JOptionPane.showMessageDialog(this, "Chamba Nafi");
    }//GEN-LAST:event_btnOperaciones2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda1;
    private javax.swing.JButton btnAyuda2;
    private javax.swing.JButton btnOperaciones1;
    private javax.swing.JButton btnOperaciones2;
    private javax.swing.JButton btnPaginaCuenta1;
    private javax.swing.JButton btnPaginaCuenta2;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblFolio;
    private javax.swing.JLabel lblFolioOperacion;
    private javax.swing.JLabel lblIcono1;
    private javax.swing.JLabel lblIcono2;
    private javax.swing.JLabel lblOperacionExitosa;
    private javax.swing.JLabel lblVoyage1;
    private javax.swing.JLabel lblVoyage2;
    private javax.swing.JPanel pnlBanner2;
    private javax.swing.JPanel pnlBanner3;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatosCuenta;
    // End of variables declaration//GEN-END:variables
}
