
package org.itson.banco.presentacion;

import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.itson.banco.dtos.ClienteDTO;
import org.itson.banco.dtos.CuentaDTO;
import org.itson.banco.dtos.TransferenciaDTO;
import org.itson.banco.negocio.CuentaBO;
import org.itson.banco.negocio.NegocioException;
import org.itson.banco.negocio.TransferenciaBO;
import org.itson.banco.persistencia.ClienteDAO;
import org.itson.banco.persistencia.ConexionBD;
import org.itson.banco.persistencia.CuentaDAO;
import org.itson.banco.persistencia.TransferenciaDAO;

/**
 *
 * @author emyla
 */
public class TransferenciaFORM extends javax.swing.JFrame {

    private static final Logger LOGGER = Logger.getLogger(TransferenciaFORM.class.getName());
    private final ControladorTransferencia controlador;
    private final CuentaDTO cuentaOrigen;
    private final ClienteDTO cliente;
    
    
    /**
     * Creates new form TransferenciaFORM
     */
    public TransferenciaFORM(ControladorTransferencia controlador, ClienteDTO cliente, CuentaDTO cuentaOrigen) {
        this.controlador = controlador;
        this.cuentaOrigen = cuentaOrigen;
        this.cliente = cliente;
        initComponents();
        setLocationRelativeTo(null);
        cargarCuentaOrigen();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBanner12 = new javax.swing.JPanel();
        btnOperaciones11 = new javax.swing.JButton();
        btnPaginaCuenta22 = new javax.swing.JButton();
        btnEditarDatos11 = new javax.swing.JButton();
        btnPaginaCuenta23 = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        pnlDatosCuenta = new javax.swing.JPanel();
        lblCuentaOrigen = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        lblCuentaDestino = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtCuentaOrigen = new javax.swing.JTextField();
        txtCuentaDestino = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        lblCuentaOrigen2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblPesosDisponibles = new javax.swing.JLabel();
        lblSaldoDisponible = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBanner12.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanner12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlBanner12.setAlignmentY(0.0F);

        btnOperaciones11.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnOperaciones11.setText("Operaciones");
        btnOperaciones11.setToolTipText("");
        btnOperaciones11.setBorder(null);
        btnOperaciones11.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnOperaciones11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperaciones11ActionPerformed(evt);
            }
        });

        btnPaginaCuenta22.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnPaginaCuenta22.setText("Cuentas");
        btnPaginaCuenta22.setToolTipText("");
        btnPaginaCuenta22.setBorder(null);
        btnPaginaCuenta22.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaCuenta22ActionPerformed(evt);
            }
        });

        btnEditarDatos11.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnEditarDatos11.setText("Perfil");
        btnEditarDatos11.setToolTipText("");
        btnEditarDatos11.setBorder(null);
        btnEditarDatos11.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnEditarDatos11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDatos11ActionPerformed(evt);
            }
        });

        btnPaginaCuenta23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPaginaCuenta23.setText("VOYAGE");
        btnPaginaCuenta23.setToolTipText("");
        btnPaginaCuenta23.setBorder(null);
        btnPaginaCuenta23.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnPaginaCuenta23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaCuenta23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBanner12Layout = new javax.swing.GroupLayout(pnlBanner12);
        pnlBanner12.setLayout(pnlBanner12Layout);
        pnlBanner12Layout.setHorizontalGroup(
            pnlBanner12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner12Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnPaginaCuenta23, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnPaginaCuenta22, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnOperaciones11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnEditarDatos11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        pnlBanner12Layout.setVerticalGroup(
            pnlBanner12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnPaginaCuenta23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnPaginaCuenta22)
                .addComponent(btnOperaciones11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarDatos11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatos.setBackground(new java.awt.Color(217, 217, 217));

        pnlDatosCuenta.setBackground(new java.awt.Color(255, 255, 255));

        lblCuentaOrigen.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblCuentaOrigen.setText("Cuenta origen");

        btnContinuar.setBackground(new java.awt.Color(200, 217, 230));
        btnContinuar.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        lblCuentaDestino.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblCuentaDestino.setText("Cuenta destino");

        lblTitulo.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblTitulo.setText("Realizar transferencia");

        txtCuentaOrigen.setEditable(false);

        lblCuentaOrigen2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblCuentaOrigen2.setText("Monto");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblPesosDisponibles.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblPesosDisponibles.setText("$00.00");

        lblSaldoDisponible.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblSaldoDisponible.setText("Saldo Disponible");

        javax.swing.GroupLayout pnlDatosCuentaLayout = new javax.swing.GroupLayout(pnlDatosCuenta);
        pnlDatosCuenta.setLayout(pnlDatosCuentaLayout);
        pnlDatosCuentaLayout.setHorizontalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCuentaOrigen2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldoDisponible)
                    .addComponent(lblPesosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCuentaLayout.createSequentialGroup()
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))))
        );
        pnlDatosCuentaLayout.setVerticalGroup(
            pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo)
                .addGap(8, 8, 8)
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuentaOrigen)
                    .addComponent(lblCuentaDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                        .addComponent(lblCuentaOrigen2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosCuentaLayout.createSequentialGroup()
                        .addComponent(lblSaldoDisponible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPesosDisponibles)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnContinuar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(pnlBanner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlBanner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(288, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed

        TransferenciaBO transferenciaBO = new TransferenciaBO(new TransferenciaDAO(new ConexionBD()));
        
        String numeroCuentaDestino = txtCuentaDestino.getText();
        String montoString = txtMonto.getText();
        
        double monto = 0;
        
        
        try {
             monto = Double.parseDouble(montoString);
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException("Error al capturar monto", ex);
        }
        
        TransferenciaDTO transferenciaDTO = new TransferenciaDTO(
                cuentaOrigen.getNumeroCuenta(),
                numeroCuentaDestino,
                monto
        );
        
        try {
            transferenciaBO.confirmarTransferencia(transferenciaDTO, cuentaOrigen);
            controlador.abrirConfirmarTransferencia(transferenciaDTO);
            this.dispose();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de transferencia", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de querer volver?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            // Acción si el usuario dice SÍ
            controlador.loginExitoso(cliente);
            this.dispose(); // cerrar ventana actual
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnOperaciones11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperaciones11ActionPerformed
        controlador.abrirHistorial();
        this.dispose();
    }//GEN-LAST:event_btnOperaciones11ActionPerformed

    private void btnPaginaCuenta22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuenta22ActionPerformed
        controlador.loginExitoso(cliente);
        this.dispose();
    }//GEN-LAST:event_btnPaginaCuenta22ActionPerformed

    private void btnEditarDatos11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatos11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarDatos11ActionPerformed

    private void btnPaginaCuenta23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaCuenta23ActionPerformed
        controlador.abrirInicioCliente(cliente);
        this.dispose();
    }//GEN-LAST:event_btnPaginaCuenta23ActionPerformed

    private void cargarCuentaOrigen() {
        txtCuentaOrigen.setText(String.valueOf(cuentaOrigen.getNumeroCuenta()));
        txtCuentaOrigen.setEditable(false);
        String saldoActual = String.valueOf(cuentaOrigen.getSaldoCuenta());
        lblPesosDisponibles.setText("$ " + saldoActual);
        
    }
    
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnEditarDatos11;
    private javax.swing.JButton btnOperaciones11;
    private javax.swing.JButton btnPaginaCuenta22;
    private javax.swing.JButton btnPaginaCuenta23;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblCuentaDestino;
    private javax.swing.JLabel lblCuentaOrigen;
    private javax.swing.JLabel lblCuentaOrigen2;
    private javax.swing.JLabel lblPesosDisponibles;
    private javax.swing.JLabel lblSaldoDisponible;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBanner12;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatosCuenta;
    private javax.swing.JTextField txtCuentaDestino;
    private javax.swing.JTextField txtCuentaOrigen;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
